# 52 - 6 words quotes
'''
done as
simple quotes T-1
'''
quotes = ["Every twenty years I reinvent myself.","I have time to fix this.","Fearlessness is the mother of reinvention.","This is your year to sparkle.","Be your own person, be unique.","Still fit into high school earrings.","I made a choice about business.","You got to nourish to flourish.","What's the stop sign mean again?","Change what you are complaining about.","Don’t wait for opportunity. Create it!","A decision was made, I complied.","I live my best life now.","I'm figuring it out by myself.","Recipe for failure. Changed my ingredients.","Talking without action is just complaining.","Stay patient and trust your journey.","I am this now and always.","I stopped getting my piano tuned.","Be young while you still can.","Associate with people who inspire you.","I learned mechanics in rocket league.","Every problem has a creative solution.","Someone has to do the paperwork.","Lost in wilderness, he found himself.","Normal is boring, weird is fun.","Boisterous gas freed, relief, remorse, pride!","Nothing to declare. Much to remember.","Lovers gonna love, haters gonna hate.","Sharp new yellow pencil. Limitless potential.","Spongebob is my one true love.","Apathetic prophet makes a pathetic profit.","Lost my wallet, found my desires.","Insomnia gives me time to think.","Married, till fatness do us part.","Say something nice or don't talk.","Coffee before art, goodbye straight lines.","I got it from my mama.","Painfully, he changed is to was.","Protect your dreams from your nightmare.","Lightning hides the color of night.","Honestly, all crows are not ravens.","Sorry soldier, shoes sold in pairs.","Love hurts because it holds hearts.","Voyager still transmitted, but Earth didn’t.","Seed becomes a tree, son becomes stranger.","Power does not pardon, power punishes.","I asked, you answered in silence.","Sometimes pretty birds cannot sing well.","Tripped over luck, stumbled upon tragedy.","Recover never really ends, does it?"]

# 37 - life quotes
quotes = ["The purpose of our lives is to be happy.","Get busy living or get busy dying.", "Never let the fear of striking out keep you from playing the game.", "The unexamined life is not worth living." ,"Turn your wounds into wisdom." , "I like criticism. It makes you strong." , "Live for each second without hesitation." ,"Life is really simple, but men insist on making it complicated.","The healthiest response to life is joy." ,"Keep calm and carry on." ,"Life is a flower of which love is the honey.","Life would be tragic if it weren’t funny." ,"The greatest pleasure of life is love." ,"Every strike brings me closer to the next home run." ,"Life shrinks or expands in proportion to one’s courage." ,"Life is short, and it is here to be lived." ,"The longer I live, the more beautiful life becomes.","Every moment is a fresh beginning." ,"When you cease to dream you cease to live.","The best way to predict your future is to create it.","There are no mistakes, only opportunities." ,"Never take life seriously. Nobody gets out alive anyway.","Be happy for this moment. This moment is your life." ,"Life’s tough, but it’s tougher when you’re stupid." ,"Nothing is more honorable than a grateful heart." ,"Happy is the man who can make a living by his hobby.","Be where you are; otherwise you will miss your life.","Living an experience, a particular fate, is accepting it fully.","As you know, life is an echo; we get what we give." ,"There are no regrets in life, just lessons." ,"Find people who will make you better." ,"If we don’t change, we don’t grow. If we don’t grow, we aren’t really living.","Life doesn’t require that we be the best, only that we try our best.","Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.","Today, you have 100% of your life left." ,"Nobody who ever gave his best regretted it." ,"Make each day your masterpiece."]

